import type { BreedCopy } from "./types";

const plural = (n: number, one: string, many: string) => (n === 1 ? one : many);

const en: BreedCopy = {
  breeds: {
    border_collie: {
      name: "Border Collie",
      metaDescription:
        "Border Collie needs from sourced data: exercise, grooming, meals, size, lifespan and who it suits — plus how PetPrep simulates the breed.",
      intro: [
        "The Border Collie is a medium-sized herding dog from Great Britain, built for endurance and hard work. Its breed standard describes a keen, alert, responsive and intelligent dog that is neither nervous nor aggressive.",
        "Kennel clubs and vets agree on one thing above all: this is a very high-energy breed. It needs more than two hours of exercise every day and plenty to think about. When it is bored or under-exercised it finds its own jobs — chewing whatever is in reach, or trying to herd children at play.",
      ],
      introSources: ["S1", "S2", "S4", "S5", "S7"],
    },
    labrador_retriever: {
      name: "Labrador Retriever",
      alsoKnownAs: "Labrador",
      metaDescription:
        "Labrador Retriever needs from sourced data: exercise, grooming, meals, size, lifespan, health notes and who it suits — plus how PetPrep simulates the breed.",
      intro: [
        "The Labrador Retriever is a large, strongly built gundog from Great Britain, bred to retrieve. Its standard describes a good-tempered, kindly and adaptable companion that is keen to please and loves water. The coat is short and dense, in black, yellow or liver/chocolate.",
        "UK charities describe the Labrador as a family dog that bonds with the whole household when it is well socialised. It is very active and highly food-motivated: treats help with training, but Labradors are also prone to putting on weight.",
      ],
      introSources: ["S48", "S49", "S50", "S53", "S59"],
    },
    golden_retriever: {
      name: "Golden Retriever",
      alsoKnownAs: "Golden",
      metaDescription:
        "Golden Retriever needs from sourced data: exercise, grooming, meals, size, lifespan, health notes and who it suits — plus how PetPrep simulates the breed.",
      intro: [
        "The Golden Retriever is a large gundog from Great Britain with a flat or wavy coat in shades of gold or cream. Its standard describes a biddable, intelligent dog that is kindly, friendly and confident.",
        "UK charities call it a great family dog for an active family, and one that can be a good first dog. The trade-offs are clear in the sources: at least two hours of exercise a day, brushing several times a week, and a coat that sheds a lot.",
      ],
      introSources: ["S63", "S64", "S65", "S66", "S68", "S69"],
    },
  },
  availability: {
    in_app: { label: "In the app", text: "Available in the 12-week PetPrep Challenge (paid breed)." },
    coming_soon: { label: "Coming soon to the app", text: "Built and tested; it arrives with the next app release." },
  },
  overview: {
    filterTitle: "Find a breed for your family",
    filterIntro: "Choose what matters to you. The tags are the same as in the app, and each one is backed by a source.",
    filterClear: "Show all",
    filterResult: (shown, total) => `${shown} of ${total} breeds`,
    filterNone: "No breed in the register matches all the selected tags yet.",
    notYet: (tags) => `No breed in the register is tagged for ${tags} yet.`,
    compareTitle: "Compare breeds",
    compareIntro: "Needs side by side, from the same sources as the breed pages.",
    compareNote: "Values are given as the named source states them. Where sources differ, the breed page lists each one.",
    open: (name) => `${name}: needs, game rules and sources`,
    mixedTitle: "Free plan: mixed breed",
    mixedText: (steps) =>
      `The free plan uses a medium-sized mixed breed. It has no breed page: a mixed breed has no breed standard, so the game uses general guidance for dogs (adult step goal: ${steps} a day).`,
    catsLine: "Cats are coming soon.",
    methodTitle: "How we build this register",
    method: [
      "Every fact comes from a named source — kennel clubs, veterinary charities, veterinary associations and peer-reviewed studies — and links to it. Breed standards are summarised in our own words.",
      "Values that no source supports are never shown as facts. Where PetPrep has to choose a number for the game, it appears only under “How PetPrep simulates it”, labelled as a game rule.",
      "The same data drives the app: the tags, meal counts and step goals on these pages are the ones the pet in the app uses.",
      "This register is not veterinary advice. Health information is for orientation only and has not been reviewed by a vet.",
    ],
  },
  rows: {
    availability: "In PetPrep",
    size: "Size",
    weight: "Adult weight",
    height: "Height at the withers",
    exercise: "Daily exercise",
    grooming: "Grooming",
    coat: "Coat",
    shedding: "Shedding",
    lifespan: "Lifespan",
    growth: "Adult weight reached",
    stepGoal: "Adult step goal in PetPrep (game rule)",
  },
  page: {
    eyebrow: "Breed register",
    backToRegister: "All breeds",
    suitabilityTitle: "Who it suits",
    suitabilityNote: "The same tags as in the app. Each tag is backed by the sources listed at the bottom of the page.",
    needsTitle: "What it needs",
    needsIntro: "From breed standards, kennel clubs and veterinary charities. Where sources differ, each one is shown.",
    cards: {
      exercise: "Exercise",
      grooming: "Coat and grooming",
      feeding: "Meals",
      lifespan: "Lifespan",
      stages: "Life stages",
      size: "Size and weight",
      training: "Training",
    },
    noData: "Not in our sources yet.",
    feedingGeneral: "General guidance for dogs (not breed-specific):",
    foodMotivated: "Strongly motivated by food — useful in training, but watch the portions.",
    stagesText: (puppy, young, seniorShare) =>
      `Veterinary life stages: puppy until about ${puppy} months, young adult until ${young} years, senior in the last ${seniorShare} of the expected lifespan.`,
    growth: (months) => `Reaches adult weight at about ${months} (guidance for its size class).`,
    coren: (rank) => `No. ${rank} in Stanley Coren's ranking of working and obedience intelligence.`,
    fci: (number, group, origin) => `FCI standard no. ${number}, group ${group}; origin: ${origin}.`,
    simTitle: "How PetPrep simulates it",
    simBadge: "Game rules, not veterinary advice",
    simIntro:
      "In PetPrep one real week is one month of the dog's life. These are the rules the game uses for this breed. PetPrep chose them from the sources on this page; they are not care instructions for a real dog.",
    simTable: { stage: "Life stage", starts: "Starts", meals: "Meals a day", steps: "Daily step goal" },
    stage: { puppy: "Puppy", young: "Young dog", adult: "Adult", senior: "Senior" },
    simArrives: (m) => `arrives at ${m} months`,
    simFromMonth: (m, years) => (years ? `month ${m} (${years})` : `month ${m}`),
    simPuppyMeals: (m4, m3, from3, m2, from6) => `${m4}; from month ${from3}: ${m3}; from month ${from6}: ${m2}`,
    simGrowingSteps: (perMonth, first, cap, capMonth) => `${perMonth} per month of age (${first} on arrival), up to ${cap} from month ${capMonth}`,
    simStepsRule: (minutes, steps, perMinute) =>
      `Step goal = minutes of daily exercise × ${perMinute} steps: an adult gets ${minutes}, so ${steps} a day.`,
    simLearning: (m) => `Learns commands ${m}× as fast as the mixed breed of the free plan.`,
    simSenior: (months, years) => `Becomes a senior in month ${months} (${years}) — the last quarter of the breed's median lifespan.`,
    simNote: "Walks count real steps from the phone's motion sensor — no GPS.",
    simDecisions: "Each game number is a PetPrep decision recorded with its sources.",
    healthTitle: "Health",
    healthNote: "For information only, not vet-reviewed. Ask your vet about your own dog.",
    healthNone: "Our sources do not include breed-specific health information for this breed yet.",
    health: {
      weight_gain: "Puts on weight easily — portions and treats need watching.",
      hip_elbow_dysplasia_eye_conditions: "Can be prone to hip and elbow dysplasia and to several inherited eye conditions.",
      cancer_risk: "Sources describe a higher risk of cancer in this breed.",
    },
    sourcesTitle: "Sources",
    sourcesIntro: (date) => `Every fact on this page cites one of these sources. The research behind them started on ${date}.`,
    sourceLabel: (id, publisher) => `Source ${id}: ${publisher}`,
    disclaimer: "PetPrep is a simulation for families. This page is not veterinary advice — for a real dog, ask a vet or the breed club.",
  },
  values: {
    size: { medium: "Medium", large: "Large" },
    coat: { "moderately long": "moderately long", smooth: "smooth (short)", short: "short", medium: "medium length" },
    grooming: {
      "once a week": "brushing once a week",
      "more than once a week": "brushing more than once a week",
      moderate: "moderate grooming needs",
      high: "high grooming needs",
    },
    shedding: { yes: "sheds", high: "sheds a lot" },
    fciGroup: { 1: "1 (sheepdogs and cattle dogs)", 8: "8 (retrievers, flushing dogs and water dogs)" },
    origin: { GB: "Great Britain" },
    or: " or ",
    males: "males",
    females: "females",
    femalesNote: { "slightly less": "females slightly smaller" },
    mean: "measured average",
    median: (y) => `median ${y}`,
    moreThanYears: (y) => `more than ${y}`,
    moreThan: (d) => `more than ${d}`,
    atLeast: (d) => `at least ${d}`,
    hours: (n) => `${n} ${plural(n, "hour", "hours")}`,
    minutes: (n) => `${n} ${plural(n, "minute", "minutes")}`,
    years: (n) => `${n} years`,
    months: (n) => `${n} months`,
    steps: (n) => `${n} steps`,
    perDay: " a day",
    mealsExact: (n) => `${n} ${plural(n, "meal", "meals")} a day`,
    mealsAtLeast: (n) => `at least ${n} meals a day`,
    mealsSmaller: (a, b) => `smaller meals, ${a}–${b} times a day`,
    mealsStage: {
      puppy_8_12_weeks: "8–12 weeks",
      puppy_3_6_months: "3–6 months",
      puppy_6_12_months: "6–12 months",
      adult: "Adult",
      senior: "Senior",
    },
  },
};

export default en;
